locations:
  lobby:
  kit_editor:
networking:
  mongo:
    uri: "uri"
    database: "db"
    profiles_collection: "practice_profiles"
    statistics_collection: "practice_profile_statistics"
    match_records_collection: "practice_match_records"
  redis:
    host: "127.0.0.1"
    port: 6379
npc_ids:
  unranked: 0
  ranked: 1
  statistics: 2
  leaderboards: 3
scoreboard:
  title: "&6Practice"
  ip: "&7&opvp.camp"