main: camp.pvp.practice.Practice
name: ${project.name}
version: ${project.version} ${git.branch}-${git.commit.id.abbrev}
author: leuo
depend:
  - Citizens
  - Gooey2
  - ProtocolLib
  - Apollo-Bukkit
  - Core

commands:
  accept:
    description: Accepts a duel from a player or team.
  arena:
    permission: practice.commands.arena
    description: Arena configuration utility.
  arenaposition:
    aliases: [apos, aposition, ap]
    permission: practice.commands.arenaposition
    description: Select a position for an arena at your current location.
  build:
    description: Toggles build mode for staff.
    permission: practice.staff.build_mode
  duel:
    description: Duel another player or team.
  elomanager:
    permission: practice.staff.elo
    description: Manage the ELO of a player.
  event:
    description: Join, leave, or host event.
  explode:
    permission: practice.commands.explode
    description: Explode a player.
  gamedebug:
    permission: practice.commands.gamedebug
    description: Miscellaneous game debugging utilities.
  games:
    permission: practice.commands.games
    description: Gets all active games.
  leaderboards:
    aliases: [leaderboard, lb, elo]
    description: View player leaderboards.
  matches:
    aliases: [mhistory, matchhistory, matchhist, duelhistory, duelhist, dhist, dh, mh]
    description: View the duel history of a player.
  party:
    aliases: [p]
    description: Manage your party.
  ping:
    description: Check a player's ping.
  playertime:
    aliases: [ptime, day, night, sunset]
    description: Changes the time of day for yourself.
  postgameinventory:
    description: Opens the post game inventory GUI.
  practiceutil:
    aliases: [putil, putils, pu]
    permission: practice.commands.practiceutil
    description: General staff utility command.
  ride:
    permission: practice.commands.ride
    description: Ride a player.
  settings:
    aliases: [options]
    description: General server settings.
  spectate:
    aliases: [spec, staffspectate]
    description: Spectate a game.
  statistics:
    aliases: [stats]
    description: View the statistics of yourself or another player.
  surrender:
    description: Surrender a game.
    aliases: [forfeit, suicide, giveup, imdone]
  tournament:
    description: Join, leave, or host a tournament.
  whereami:
    description: Shows debug information about your player.
    permission: practice.commands.whereami

permissions:
  # General Staff Permissions
  practice.staff:
    description: Staff permissions for Practice.
  practice.admin:
    description: Admin permissions for Practice.
    children:
      practice.*: true
  # Donator Permissions
  practice.cosmetics.death_animation:
    description: Allows a player to change their death animation.
  practice.cosmetics.sidebar_settings:
    description: Allows a player to customize their sidebar settings.
  practice.duel_requests.map_selection:
    description: Allows a player to select a map for duel requests.
  practice.lobby.fly:
    description: Allows a player to fly in the lobby.

  # Commands
  practice.commands.arena:
    description: Allows the player to use the arena command.
  practice.commands.arenaposition:
    description: Allows the player to use the arenaposition command.
  practice.commands.explode:
    description: Allows the player to use the explode command.
