main: camp.pvp.Practice
name: Practice
version: ${plugin.desc}
author: leuo
depend:
  - Gooey2
  - NetworkHelper
  - ProtocolLib
  - LunarClient-API

commands:
  accept:
    description: Accepts a duel from a player or team.
  arena:
    description: Arena configuration utility.
  build:
    description: Toggles build mode for staff.
    permission: practice.staff.build_mode
  duel:
    description: Duel another player or team.
  event:
    description: Host an event.
  games:
    description: Gets all active games.
  leaderboards:
    aliases: [leaderboard, lb, elo]
    description: View player leaderboards.
  party:
    aliases: [p]
    description: Manage your party.
  ping:
    description: Check a player's ping.
  playertime:
    aliases: [ptime, day, night, sunset]
    description: Changes the time of day for yourself.
  postgameinventory:
    description: Opens the post game inventory GUI.
  practiceutil:
    aliases: [putil, putils, pu]
    description: General staff utility command.
  settings:
    aliases: [options]
    description: General server settings.
  spectate:
    aliases: [spec]
    description: Spectate a game.
  statistics:
    aliases: [stats]
    description: View the statistics of yourself or another player.