main: camp.pvp.practice.Practice
name: Practice
version: ${git.branch}-${git.commit.id.abbrev}
author: leuo
depend:
  - Citizens
  - Gooey2
  - ProtocolLib
  - Apollo-Bukkit

commands:
  accept:
    description: Accepts a duel from a player or team.
  arena:
    permission: practice.commands.arena
    description: Arena configuration utility.
  arenaposition:
    aliases: [apos, aposition, ap]
    permission: practice.commands.arenaposition
    description: Select a position for an arena at your current location.
  build:
    description: Toggles build mode for staff.
    permission: practice.staff.build_mode
  duel:
    description: Duel another player or team.
  elomanager:
    permission: practice.staff.elo
    description: Manage the ELO of a player.
  event:
    description: Join, leave, or host event.
  gamedebug:
    permission: practice.commands.gamedebug
    description: Miscellaneous game debugging utilities.
  games:
    permission: practice.commands.games
    description: Gets all active games.
  leaderboards:
    aliases: [leaderboard, lb, elo]
    description: View player leaderboards.
  party:
    aliases: [p]
    description: Manage your party.
  ping:
    description: Check a player's ping.
  playertime:
    aliases: [ptime, day, night, sunset]
    description: Changes the time of day for yourself.
  postgameinventory:
    description: Opens the post game inventory GUI.
  practiceutil:
    aliases: [putil, putils, pu]
    permission: practice.commands.practiceutil
    description: General staff utility command.
  ride:
    permission: practice.commands.ride
    description: Ride a player.
  settings:
    aliases: [options]
    description: General server settings.
  spectate:
    aliases: [spec]
    description: Spectate a game.
  stats:
    description: View the statistics of yourself or another player.
  tournament:
    description: Join, leave, or host a tournament.
  whereami:
    description: Shows debug information about your player.
    permission: practice.commands.whereami